server:
  port: 9090

spring:
  application:
    name: Api_Gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

JWT:
  SECRET: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  EXPIRATION: 604800000