spring:

  application:
    name: auth-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurances
    username: postgres
    password: 123456

server:
  port: 8085

JWT:
  SECRET: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  EXPIRATION: 604800000
